sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - wget -O- http://neuro.debian.net/lists/trusty.de-md.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9
  - sudo apt-get update
  - sudo apt-get install fsl
script:
  - env LD_LIBRARY_PATH=/usr/lib/fsl/5.0 make tests
